//! The event bus, and the sinks that persist a match.
//!
//! One enum crosses this crate: `schema::Event`. Wire frames, the replay log and
//! the database are all derived from the same stream, so the viewer and the
//! database cannot disagree.
//!
//! # What a match writes
//!
//! Two artefacts, split by whether losing them to a code change matters.
//!
//! The **replay log** records the *inputs* — a seed, a configuration hash, and the
//! per-tick [`schema::Inputs`] that `World::step` consumes. Everything else is
//! regenerated by re-running the simulation. The arena holds two thousand entities
//! but only twelve decide anything, so recording decisions rather than consequences
//! is about three orders of magnitude smaller: a ninety-minute match is tens of
//! megabytes instead of tens of gigabytes. This works because determinism is an
//! invariant of this project rather than an accident, and it is exact rather than
//! lossy.
//!
//! The **database** records discrete events and the score timeline. These are the
//! analytical facts — who killed what, which focus a shape came from, when the lead
//! changed — and they are not cheaply regenerable once the simulation changes. They
//! are written permanently for that reason.
//!
//! Kinematics are written by neither. Trajectories are bulk derived data; a
//! re-simulation rebuilds them at whatever rate and filter is wanted.
//!
//! # The catch, stated plainly
//!
//! A replay stops reproducing when the physics changes. `Event::MatchStart` carries
//! a `config_hash` so this is detectable rather than silent, but detection is not a
//! fix. Anything that must outlive a code change belongs in the database.

pub mod replay;
pub mod sqlite;

pub use replay::{ReplayReader, ReplaySink};
pub use sqlite::SqliteSink;

use schema::{Event, Inputs, Tick};

/// Everything one tick produced, offered to every sink.
///
/// `docs/DESIGN.md` writes the sink method as `accept(tick, events: &[Event])`.
/// That signature cannot carry the inputs a replay is made of, and a replay of
/// events alone would not reproduce a match. The record carries both, and each sink
/// takes what it needs.
pub struct TickRecord<'a> {
    pub tick: Tick,
    /// Discrete events, in emission order.
    pub events: &'a [Event],
    /// What the agents decided this tick. The replay payload.
    pub inputs: &'a Inputs,
    pub scores: [u32; 2],
}

/// A consumer of the event stream.
pub trait Sink: Send {
    fn accept(&mut self, rec: &TickRecord<'_>);
    /// Commit whatever is buffered. Must be safe to call more than once.
    fn flush(&mut self);
}

/// Fans one record out to every registered sink.
///
/// Registration order is fan-out order, and it is stable, so two runs write their
/// artefacts in the same sequence.
#[derive(Default)]
pub struct Bus {
    sinks: Vec<Box<dyn Sink>>,
}

impl Bus {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with(mut self, sink: Box<dyn Sink>) -> Self {
        self.sinks.push(sink);
        self
    }

    pub fn push(&mut self, sink: Box<dyn Sink>) {
        self.sinks.push(sink);
    }

    pub fn len(&self) -> usize {
        self.sinks.len()
    }

    pub fn is_empty(&self) -> bool {
        self.sinks.is_empty()
    }

    pub fn publish(&mut self, rec: &TickRecord<'_>) {
        for sink in &mut self.sinks {
            sink.accept(rec);
        }
    }

    pub fn flush(&mut self) {
        for sink in &mut self.sinks {
            sink.flush();
        }
    }
}
